#include "common.h"
#include "typedefs.h"
#include "enums.h"
#include "item_ctl.h"

#include "graphics/graph2d/effect.h"
#include "ingame/event/ev_main.h"
#include "ingame/ig_glob.h"
#include "ingame/map/find_ctl.h"
#include "ingame/map/item_ctl.h"
#include "ingame/menu/item.h"
#include "ingame/menu/item_get.h"
#include "ingame/plyr/unit_ctl.h"
#include "main/glob.h"

MAP_ITEM_DAT map_item_dat[162] = {
    {
        .item_no = 37,
        .stts = 1,
        .room = 17,
        .msn_no = 129,
        .pos_x = 2160,
        .pos_y = 0,
        .pos_z = 559,
        .get_msg = {70, 71},
    },
    {
        .item_no = 63,
        .stts = 129,
        .room = 22,
        .msn_no = 129,
        .pos_x = 7135,
        .pos_y = 0,
        .pos_z = 2434,
        .get_msg = {94, 95},
    },
    {
        .item_no = 38,
        .stts = 128,
        .room = 3,
        .msn_no = 128,
        .pos_x = 1700,
        .pos_y = -1400,
        .pos_z = 4500,
        .get_msg = {88, 89},
    },
    {
        .item_no = 18,
        .stts = 128,
        .room = 12,
        .msn_no = 129,
        .pos_x = 1800,
        .pos_y = -430,
        .pos_z = 3759,
        .get_msg = {90, 91},
    },
    {
        .item_no = 34,
        .stts = 1,
        .room = 29,
        .msn_no = 130,
        .pos_x = 3936,
        .pos_y = 3000,
        .pos_z = 3112,
        .get_msg = {106, 107},
    },
    {
        .item_no = 48,
        .stts = 128,
        .room = 35,
        .msn_no = 130,
        .pos_x = 2433,
        .pos_y = -150,
        .pos_z = 2166,
        .get_msg = {108, 109},
    },
    {
        .item_no = 47,
        .stts = 130,
        .room = 36,
        .msn_no = 130,
        .pos_x = 1027,
        .pos_y = -375,
        .pos_z = 3099,
        .get_msg = {110, 111},
    },
    {
        .item_no = 46,
        .stts = 128,
        .room = 14,
        .msn_no = 130,
        .pos_x = 2374,
        .pos_y = -150,
        .pos_z = 3014,
        .get_msg = {112, 113},
    },
    {
        .item_no = 1,
        .stts = 128,
        .room = 20,
        .msn_no = 132,
        .pos_x = 2490,
        .pos_y = 70,
        .pos_z = 2600,
        .get_msg = {90, 91},
    },
    {
        .item_no = 1,
        .stts = 128,
        .room = 20,
        .msn_no = 132,
        .pos_x = 7360,
        .pos_y = -70,
        .pos_z = 4050,
        .get_msg = {90, 91},
    },
    {
        .item_no = 65,
        .stts = 128,
        .room = 26,
        .msn_no = 129,
        .pos_x = 1355,
        .pos_y = -425,
        .pos_z = 2049,
        .get_msg = {116, 117},
    },
    {
        .item_no = 65,
        .stts = 130,
        .room = 26,
        .msn_no = 130,
        .pos_x = 4912,
        .pos_y = 30,
        .pos_z = 5005,
        .get_msg = {116, 117},
    },
    {
        .item_no = 12,
        .stts = 129,
        .room = 21,
        .msn_no = 130,
        .pos_x = 5824,
        .pos_y = -420,
        .pos_z = 3586,
        .get_msg = {0, 0},
    },
    {
        .item_no = 12,
        .stts = 129,
        .room = 14,
        .msn_no = 131,
        .pos_x = 2327,
        .pos_y = -820,
        .pos_z = 4660,
        .get_msg = {0, 0},
    },
    {
        .item_no = 17,
        .stts = 0,
        .room = 35,
        .msn_no = 132,
        .pos_x = 366,
        .pos_y = -150,
        .pos_z = 1460,
        .get_msg = {87, 88},
    },
    {
        .item_no = 57,
        .stts = 0,
        .room = 18,
        .msn_no = 132,
        .pos_x = 1690,
        .pos_y = 0,
        .pos_z = 1842,
        .get_msg = {60, 61},
    },
    {
        .item_no = 12,
        .stts = 129,
        .room = 16,
        .msn_no = 130,
        .pos_x = 5462,
        .pos_y = -20,
        .pos_z = 5657,
        .get_msg = {0, 0},
    },
    {
        .item_no = 6,
        .stts = 128,
        .room = 3,
        .msn_no = 129,
        .pos_x = 1880,
        .pos_y = -370,
        .pos_z = 1293,
        .get_msg = {0, 0},
    },
    {
        .item_no = 58,
        .stts = 1,
        .room = 34,
        .msn_no = 132,
        .pos_x = 8370,
        .pos_y = -20,
        .pos_z = 3500,
        .get_msg = {55, 59},
    },
    {
        .item_no = 58,
        .stts = 129,
        .room = 34,
        .msn_no = 132,
        .pos_x = 8370,
        .pos_y = -20,
        .pos_z = 3502,
        .get_msg = {55, 59},
    },
    {
        .item_no = 58,
        .stts = 129,
        .room = 34,
        .msn_no = 132,
        .pos_x = 8370,
        .pos_y = -20,
        .pos_z = 3498,
        .get_msg = {55, 59},
    },
    {
        .item_no = 58,
        .stts = 129,
        .room = 34,
        .msn_no = 132,
        .pos_x = 8372,
        .pos_y = -20,
        .pos_z = 3500,
        .get_msg = {55, 59},
    },
    {
        .item_no = 1,
        .stts = 0,
        .room = 0,
        .msn_no = 128,
        .pos_x = 3958,
        .pos_y = -400,
        .pos_z = 4885,
        .get_msg = {18, 54},
    },
    {
        .item_no = 6,
        .stts = 0,
        .room = 0,
        .msn_no = 129,
        .pos_x = 3957,
        .pos_y = -400,
        .pos_z = 4493,
        .get_msg = {6, 31},
    },
    {
        .item_no = 1,
        .stts = 0,
        .room = 3,
        .msn_no = 129,
        .pos_x = 3135,
        .pos_y = 0,
        .pos_z = 1276,
        .get_msg = {36, 255},
    },
    {
        .item_no = 1,
        .stts = 0,
        .room = 3,
        .msn_no = 129,
        .pos_x = 2972,
        .pos_y = 0,
        .pos_z = 472,
        .get_msg = {8, 255},
    },
    {
        .item_no = 6,
        .stts = 0,
        .room = 3,
        .msn_no = 129,
        .pos_x = 1091,
        .pos_y = -1400,
        .pos_z = 454,
        .get_msg = {6, 31},
    },
    {
        .item_no = 61,
        .stts = 0,
        .room = 11,
        .msn_no = 129,
        .pos_x = 1334,
        .pos_y = 0,
        .pos_z = 4413,
        .get_msg = {68, 69},
    },
    {
        .item_no = 6,
        .stts = 0,
        .room = 11,
        .msn_no = 129,
        .pos_x = 1997,
        .pos_y = 0,
        .pos_z = 3355,
        .get_msg = {6, 31},
    },
    {
        .item_no = 6,
        .stts = 0,
        .room = 13,
        .msn_no = 129,
        .pos_x = 4673,
        .pos_y = 0,
        .pos_z = 5060,
        .get_msg = {6, 31},
    },
    {
        .item_no = 2,
        .stts = 0,
        .room = 12,
        .msn_no = 129,
        .pos_x = 860,
        .pos_y = -180,
        .pos_z = 3900,
        .get_msg = {10, 9},
    },
    {
        .item_no = 6,
        .stts = 0,
        .room = 24,
        .msn_no = 129,
        .pos_x = 4376,
        .pos_y = -1725,
        .pos_z = 1092,
        .get_msg = {27, 255},
    },
    {
        .item_no = 8,
        .stts = 0,
        .room = 38,
        .msn_no = 129,
        .pos_x = 1859,
        .pos_y = 0,
        .pos_z = 1545,
        .get_msg = {29, 23},
    },
    {
        .item_no = 6,
        .stts = 0,
        .room = 38,
        .msn_no = 129,
        .pos_x = 2521,
        .pos_y = 0,
        .pos_z = 3048,
        .get_msg = {6, 255},
    },
    {
        .item_no = 19,
        .stts = 0,
        .room = 41,
        .msn_no = 129,
        .pos_x = 370,
        .pos_y = -500,
        .pos_z = 1712,
        .get_msg = {66, 67},
    },
    {
        .item_no = 1,
        .stts = 0,
        .room = 41,
        .msn_no = 129,
        .pos_x = 1298,
        .pos_y = -100,
        .pos_z = 2995,
        .get_msg = {52, 255},
    },
    {
        .item_no = 1,
        .stts = 0,
        .room = 1,
        .msn_no = 129,
        .pos_x = 4167,
        .pos_y = -50,
        .pos_z = 292,
        .get_msg = {4, 255},
    },
    {
        .item_no = 7,
        .stts = 0,
        .room = 1,
        .msn_no = 129,
        .pos_x = 6778,
        .pos_y = 0,
        .pos_z = 3372,
        .get_msg = {25, 255},
    },
    {
        .item_no = 2,
        .stts = 0,
        .room = 8,
        .msn_no = 129,
        .pos_x = 9575,
        .pos_y = -1820,
        .pos_z = 2370,
        .get_msg = {17, 255},
    },
    {
        .item_no = 6,
        .stts = 0,
        .room = 8,
        .msn_no = 129,
        .pos_x = 6363,
        .pos_y = -1400,
        .pos_z = -197,
        .get_msg = {6, 255},
    },
    {
        .item_no = 7,
        .stts = 0,
        .room = 9,
        .msn_no = 129,
        .pos_x = 180,
        .pos_y = -100,
        .pos_z = 2514,
        .get_msg = {37, 255},
    },
    {
        .item_no = 5,
        .stts = 0,
        .room = 9,
        .msn_no = 129,
        .pos_x = 1763,
        .pos_y = -250,
        .pos_z = 3200,
        .get_msg = {37, 255},
    },
    {
        .item_no = 6,
        .stts = 0,
        .room = 9,
        .msn_no = 129,
        .pos_x = 1120,
        .pos_y = -500,
        .pos_z = 3200,
        .get_msg = {16, 255},
    },
    {
        .item_no = 3,
        .stts = 0,
        .room = 9,
        .msn_no = 129,
        .pos_x = 3285,
        .pos_y = -1150,
        .pos_z = 2251,
        .get_msg = {28, 255},
    },
    {
        .item_no = 2,
        .stts = 0,
        .room = 9,
        .msn_no = 129,
        .pos_x = 1586,
        .pos_y = 0,
        .pos_z = 189,
        .get_msg = {37, 255},
    },
    {
        .item_no = 5,
        .stts = 0,
        .room = 9,
        .msn_no = 129,
        .pos_x = 900,
        .pos_y = -200,
        .pos_z = 408,
        .get_msg = {36, 255},
    },
    {
        .item_no = 5,
        .stts = 0,
        .room = 9,
        .msn_no = 129,
        .pos_x = 4497,
        .pos_y = -1170,
        .pos_z = 3184,
        .get_msg = {22, 255},
    },
    {
        .item_no = 2,
        .stts = 0,
        .room = 7,
        .msn_no = 129,
        .pos_x = 4318,
        .pos_y = 0,
        .pos_z = 356,
        .get_msg = {4, 255},
    },
    {
        .item_no = 5,
        .stts = 0,
        .room = 7,
        .msn_no = 129,
        .pos_x = 4026,
        .pos_y = -330,
        .pos_z = 1942,
        .get_msg = {53, 255},
    },
    {
        .item_no = 6,
        .stts = 0,
        .room = 15,
        .msn_no = 129,
        .pos_x = 2772,
        .pos_y = 0,
        .pos_z = 651,
        .get_msg = {6, 255},
    },
    {
        .item_no = 62,
        .stts = 0,
        .room = 16,
        .msn_no = 129,
        .pos_x = 2331,
        .pos_y = -125,
        .pos_z = 5749,
        .get_msg = {64, 65},
    },
    {
        .item_no = 8,
        .stts = 0,
        .room = 16,
        .msn_no = 129,
        .pos_x = 1728,
        .pos_y = 0,
        .pos_z = 6134,
        .get_msg = {44, 23},
    },
    {
        .item_no = 5,
        .stts = 0,
        .room = 16,
        .msn_no = 129,
        .pos_x = 2650,
        .pos_y = -50,
        .pos_z = 1898,
        .get_msg = {32, 255},
    },
    {
        .item_no = 5,
        .stts = 0,
        .room = 10,
        .msn_no = 129,
        .pos_x = 809,
        .pos_y = -450,
        .pos_z = 1451,
        .get_msg = {53, 255},
    },
    {
        .item_no = 5,
        .stts = 0,
        .room = 10,
        .msn_no = 129,
        .pos_x = 2600,
        .pos_y = -200,
        .pos_z = 2674,
        .get_msg = {43, 255},
    },
    {
        .item_no = 2,
        .stts = 0,
        .room = 22,
        .msn_no = 129,
        .pos_x = 2637,
        .pos_y = 0,
        .pos_z = 321,
        .get_msg = {21, 255},
    },
    {
        .item_no = 8,
        .stts = 0,
        .room = 22,
        .msn_no = 129,
        .pos_x = 4605,
        .pos_y = 0,
        .pos_z = 5147,
        .get_msg = {22, 23},
    },
    {
        .item_no = 20,
        .stts = 0,
        .room = 21,
        .msn_no = 129,
        .pos_x = 5890,
        .pos_y = -450,
        .pos_z = 3505,
        .get_msg = {62, 63},
    },
    {
        .item_no = 5,
        .stts = 0,
        .room = 21,
        .msn_no = 129,
        .pos_x = 6530,
        .pos_y = 0,
        .pos_z = 1381,
        .get_msg = {25, 255},
    },
    {
        .item_no = 8,
        .stts = 0,
        .room = 21,
        .msn_no = 129,
        .pos_x = 6494,
        .pos_y = 0,
        .pos_z = 4377,
        .get_msg = {25, 23},
    },
    {
        .item_no = 6,
        .stts = 0,
        .room = 23,
        .msn_no = 129,
        .pos_x = 190,
        .pos_y = 0,
        .pos_z = 1500,
        .get_msg = {4, 255},
    },
    {
        .item_no = 8,
        .stts = 0,
        .room = 25,
        .msn_no = 129,
        .pos_x = 6014,
        .pos_y = -2025,
        .pos_z = 9016,
        .get_msg = {25, 23},
    },
    {
        .item_no = 2,
        .stts = 0,
        .room = 25,
        .msn_no = 129,
        .pos_x = 4130,
        .pos_y = -2025,
        .pos_z = 8944,
        .get_msg = {26, 255},
    },
    {
        .item_no = 5,
        .stts = 0,
        .room = 40,
        .msn_no = 130,
        .pos_x = 750,
        .pos_y = -410,
        .pos_z = 2824,
        .get_msg = {53, 255},
    },
    {
        .item_no = 1,
        .stts = 0,
        .room = 40,
        .msn_no = 130,
        .pos_x = 2549,
        .pos_y = -200,
        .pos_z = 600,
        .get_msg = {24, 255},
    },
    {
        .item_no = 6,
        .stts = 0,
        .room = 40,
        .msn_no = 130,
        .pos_x = 2571,
        .pos_y = -200,
        .pos_z = 1642,
        .get_msg = {51, 255},
    },
    {
        .item_no = 2,
        .stts = 0,
        .room = 16,
        .msn_no = 130,
        .pos_x = 3848,
        .pos_y = 0,
        .pos_z = 3974,
        .get_msg = {21, 255},
    },
    {
        .item_no = 5,
        .stts = 0,
        .room = 16,
        .msn_no = 130,
        .pos_x = 1000,
        .pos_y = -70,
        .pos_z = 6300,
        .get_msg = {20, 255},
    },
    {
        .item_no = 2,
        .stts = 0,
        .room = 7,
        .msn_no = 130,
        .pos_x = 4365,
        .pos_y = 0,
        .pos_z = 417,
        .get_msg = {18, 255},
    },
    {
        .item_no = 8,
        .stts = 0,
        .room = 27,
        .msn_no = 130,
        .pos_x = -2797,
        .pos_y = 230,
        .pos_z = 4940,
        .get_msg = {33, 255},
    },
    {
        .item_no = 6,
        .stts = 0,
        .room = 15,
        .msn_no = 130,
        .pos_x = 297,
        .pos_y = 0,
        .pos_z = 401,
        .get_msg = {27, 255},
    },
    {
        .item_no = 8,
        .stts = 0,
        .room = 17,
        .msn_no = 130,
        .pos_x = 201,
        .pos_y = 0,
        .pos_z = 1300,
        .get_msg = {11, 255},
    },
    {
        .item_no = 2,
        .stts = 0,
        .room = 17,
        .msn_no = 130,
        .pos_x = 749,
        .pos_y = 0,
        .pos_z = 7074,
        .get_msg = {18, 255},
    },
    {
        .item_no = 7,
        .stts = 0,
        .room = 22,
        .msn_no = 130,
        .pos_x = 3080,
        .pos_y = 0,
        .pos_z = 7388,
        .get_msg = {32, 255},
    },
    {
        .item_no = 8,
        .stts = 0,
        .room = 22,
        .msn_no = 130,
        .pos_x = 2955,
        .pos_y = 0,
        .pos_z = 11873,
        .get_msg = {25, 255},
    },
    {
        .item_no = 5,
        .stts = 0,
        .room = 11,
        .msn_no = 130,
        .pos_x = 2393,
        .pos_y = 0,
        .pos_z = 4222,
        .get_msg = {11, 255},
    },
    {
        .item_no = 5,
        .stts = 0,
        .room = 41,
        .msn_no = 130,
        .pos_x = 1548,
        .pos_y = 0,
        .pos_z = 2424,
        .get_msg = {52, 255},
    },
    {
        .item_no = 8,
        .stts = 0,
        .room = 38,
        .msn_no = 130,
        .pos_x = 350,
        .pos_y = -100,
        .pos_z = 350,
        .get_msg = {14, 255},
    },
    {
        .item_no = 7,
        .stts = 0,
        .room = 38,
        .msn_no = 130,
        .pos_x = 2528,
        .pos_y = 0,
        .pos_z = 1355,
        .get_msg = {39, 255},
    },
    {
        .item_no = 5,
        .stts = 0,
        .room = 38,
        .msn_no = 130,
        .pos_x = -700,
        .pos_y = -150,
        .pos_z = 3700,
        .get_msg = {11, 255},
    },
    {
        .item_no = 2,
        .stts = 0,
        .room = 8,
        .msn_no = 130,
        .pos_x = 9575,
        .pos_y = -1800,
        .pos_z = 2370,
        .get_msg = {35, 255},
    },
    {
        .item_no = 8,
        .stts = 0,
        .room = 8,
        .msn_no = 130,
        .pos_x = 5800,
        .pos_y = 0,
        .pos_z = 1750,
        .get_msg = {34, 255},
    },
    {
        .item_no = 5,
        .stts = 0,
        .room = 9,
        .msn_no = 130,
        .pos_x = 755,
        .pos_y = -330,
        .pos_z = 3100,
        .get_msg = {16, 255},
    },
    {
        .item_no = 5,
        .stts = 0,
        .room = 9,
        .msn_no = 130,
        .pos_x = 1759,
        .pos_y = 0,
        .pos_z = 598,
        .get_msg = {11, 255},
    },
    {
        .item_no = 1,
        .stts = 0,
        .room = 9,
        .msn_no = 130,
        .pos_x = 2010,
        .pos_y = -50,
        .pos_z = 1300,
        .get_msg = {36, 255},
    },
    {
        .item_no = 6,
        .stts = 0,
        .room = 1,
        .msn_no = 130,
        .pos_x = 2340,
        .pos_y = 0,
        .pos_z = 3678,
        .get_msg = {6, 255},
    },
    {
        .item_no = 1,
        .stts = 0,
        .room = 1,
        .msn_no = 130,
        .pos_x = 4192,
        .pos_y = -50,
        .pos_z = 189,
        .get_msg = {10, 255},
    },
    {
        .item_no = 3,
        .stts = 0,
        .room = 5,
        .msn_no = 130,
        .pos_x = 176,
        .pos_y = 0,
        .pos_z = 185,
        .get_msg = {18, 255},
    },
    {
        .item_no = 8,
        .stts = 0,
        .room = 6,
        .msn_no = 130,
        .pos_x = 5595,
        .pos_y = 400,
        .pos_z = 3002,
        .get_msg = {22, 255},
    },
    {
        .item_no = 5,
        .stts = 0,
        .room = 6,
        .msn_no = 130,
        .pos_x = 1876,
        .pos_y = 400,
        .pos_z = 2133,
        .get_msg = {22, 255},
    },
    {
        .item_no = 6,
        .stts = 0,
        .room = 6,
        .msn_no = 130,
        .pos_x = 1849,
        .pos_y = 0,
        .pos_z = 3133,
        .get_msg = {6, 255},
    },
    {
        .item_no = 6,
        .stts = 0,
        .room = 0,
        .msn_no = 130,
        .pos_x = 1324,
        .pos_y = 0,
        .pos_z = 1156,
        .get_msg = {27, 255},
    },
    {
        .item_no = 1,
        .stts = 0,
        .room = 14,
        .msn_no = 130,
        .pos_x = 4480,
        .pos_y = 0,
        .pos_z = 176,
        .get_msg = {18, 255},
    },
    {
        .item_no = 2,
        .stts = 0,
        .room = 13,
        .msn_no = 130,
        .pos_x = 4176,
        .pos_y = 0,
        .pos_z = 5171,
        .get_msg = {18, 255},
    },
    {
        .item_no = 5,
        .stts = 0,
        .room = 36,
        .msn_no = 130,
        .pos_x = 1750,
        .pos_y = -150,
        .pos_z = 500,
        .get_msg = {11, 255},
    },
    {
        .item_no = 7,
        .stts = 0,
        .room = 4,
        .msn_no = 130,
        .pos_x = 6616,
        .pos_y = 0,
        .pos_z = 1959,
        .get_msg = {11, 255},
    },
    {
        .item_no = 2,
        .stts = 0,
        .room = 4,
        .msn_no = 130,
        .pos_x = 128,
        .pos_y = 0,
        .pos_z = 2186,
        .get_msg = {18, 255},
    },
    {
        .item_no = 3,
        .stts = 0,
        .room = 12,
        .msn_no = 130,
        .pos_x = 1753,
        .pos_y = -410,
        .pos_z = 3900,
        .get_msg = {17, 255},
    },
    {
        .item_no = 5,
        .stts = 0,
        .room = 12,
        .msn_no = 130,
        .pos_x = 300,
        .pos_y = -620,
        .pos_z = 345,
        .get_msg = {42, 255},
    },
    {
        .item_no = 6,
        .stts = 0,
        .room = 23,
        .msn_no = 130,
        .pos_x = 190,
        .pos_y = 0,
        .pos_z = 1500,
        .get_msg = {4, 255},
    },
    {
        .item_no = 2,
        .stts = 0,
        .room = 23,
        .msn_no = 130,
        .pos_x = 3070,
        .pos_y = 0,
        .pos_z = 510,
        .get_msg = {4, 255},
    },
    {
        .item_no = 5,
        .stts = 0,
        .room = 25,
        .msn_no = 130,
        .pos_x = 6014,
        .pos_y = -2025,
        .pos_z = 9016,
        .get_msg = {25, 255},
    },
    {
        .item_no = 2,
        .stts = 0,
        .room = 25,
        .msn_no = 130,
        .pos_x = 4130,
        .pos_y = -2025,
        .pos_z = 8944,
        .get_msg = {26, 255},
    },
    {
        .item_no = 6,
        .stts = 0,
        .room = 7,
        .msn_no = 131,
        .pos_x = 4365,
        .pos_y = 0,
        .pos_z = 417,
        .get_msg = {4, 255},
    },
    {
        .item_no = 5,
        .stts = 0,
        .room = 28,
        .msn_no = 131,
        .pos_x = 7742,
        .pos_y = 1200,
        .pos_z = -6359,
        .get_msg = {11, 255},
    },
    {
        .item_no = 6,
        .stts = 0,
        .room = 28,
        .msn_no = 131,
        .pos_x = 10393,
        .pos_y = 800,
        .pos_z = -2623,
        .get_msg = {32, 255},
    },
    {
        .item_no = 5,
        .stts = 0,
        .room = 28,
        .msn_no = 131,
        .pos_x = 3009,
        .pos_y = 0,
        .pos_z = 924,
        .get_msg = {25, 255},
    },
    {
        .item_no = 1,
        .stts = 0,
        .room = 29,
        .msn_no = 131,
        .pos_x = 526,
        .pos_y = 0,
        .pos_z = 526,
        .get_msg = {26, 255},
    },
    {
        .item_no = 8,
        .stts = 0,
        .room = 27,
        .msn_no = 131,
        .pos_x = -2797,
        .pos_y = 230,
        .pos_z = 4940,
        .get_msg = {33, 255},
    },
    {
        .item_no = 8,
        .stts = 0,
        .room = 8,
        .msn_no = 131,
        .pos_x = 5800,
        .pos_y = 0,
        .pos_z = 1750,
        .get_msg = {34, 255},
    },
    {
        .item_no = 5,
        .stts = 0,
        .room = 9,
        .msn_no = 131,
        .pos_x = 1226,
        .pos_y = 0,
        .pos_z = 2226,
        .get_msg = {22, 255},
    },
    {
        .item_no = 5,
        .stts = 0,
        .room = 9,
        .msn_no = 131,
        .pos_x = 656,
        .pos_y = 0,
        .pos_z = 125,
        .get_msg = {28, 255},
    },
    {
        .item_no = 7,
        .stts = 0,
        .room = 9,
        .msn_no = 131,
        .pos_x = 180,
        .pos_y = -435,
        .pos_z = 2514,
        .get_msg = {37, 255},
    },
    {
        .item_no = 6,
        .stts = 0,
        .room = 9,
        .msn_no = 131,
        .pos_x = 175,
        .pos_y = -1180,
        .pos_z = 2700,
        .get_msg = {37, 255},
    },
    {
        .item_no = 1,
        .stts = 0,
        .room = 1,
        .msn_no = 131,
        .pos_x = 3157,
        .pos_y = -50,
        .pos_z = 312,
        .get_msg = {18, 255},
    },
    {
        .item_no = 3,
        .stts = 0,
        .room = 1,
        .msn_no = 131,
        .pos_x = 6727,
        .pos_y = 0,
        .pos_z = 3268,
        .get_msg = {18, 255},
    },
    {
        .item_no = 7,
        .stts = 0,
        .room = 1,
        .msn_no = 131,
        .pos_x = 6778,
        .pos_y = 0,
        .pos_z = 3372,
        .get_msg = {25, 255},
    },
    {
        .item_no = 5,
        .stts = 0,
        .room = 3,
        .msn_no = 131,
        .pos_x = 2262,
        .pos_y = 30,
        .pos_z = 2220,
        .get_msg = {38, 255},
    },
    {
        .item_no = 2,
        .stts = 0,
        .room = 3,
        .msn_no = 131,
        .pos_x = 248,
        .pos_y = -1400,
        .pos_z = 158,
        .get_msg = {36, 255},
    },
    {
        .item_no = 5,
        .stts = 0,
        .room = 11,
        .msn_no = 131,
        .pos_x = 2393,
        .pos_y = 0,
        .pos_z = 4222,
        .get_msg = {11, 255},
    },
    {
        .item_no = 6,
        .stts = 0,
        .room = 24,
        .msn_no = 131,
        .pos_x = 6722,
        .pos_y = -1725,
        .pos_z = 1076,
        .get_msg = {27, 255},
    },
    {
        .item_no = 5,
        .stts = 0,
        .room = 2,
        .msn_no = 131,
        .pos_x = 149,
        .pos_y = 0,
        .pos_z = 3342,
        .get_msg = {7, 255},
    },
    {
        .item_no = 6,
        .stts = 0,
        .room = 0,
        .msn_no = 131,
        .pos_x = 2037,
        .pos_y = -400,
        .pos_z = 5192,
        .get_msg = {6, 255},
    },
    {
        .item_no = 2,
        .stts = 0,
        .room = 0,
        .msn_no = 131,
        .pos_x = 1948,
        .pos_y = 0,
        .pos_z = 1472,
        .get_msg = {18, 255},
    },
    {
        .item_no = 7,
        .stts = 0,
        .room = 5,
        .msn_no = 131,
        .pos_x = 280,
        .pos_y = -400,
        .pos_z = 1642,
        .get_msg = {11, 255},
    },
    {
        .item_no = 2,
        .stts = 0,
        .room = 5,
        .msn_no = 131,
        .pos_x = 211,
        .pos_y = 0,
        .pos_z = 3109,
        .get_msg = {18, 255},
    },
    {
        .item_no = 3,
        .stts = 0,
        .room = 36,
        .msn_no = 131,
        .pos_x = 1022,
        .pos_y = -450,
        .pos_z = 3200,
        .get_msg = {41, 255},
    },
    {
        .item_no = 5,
        .stts = 0,
        .room = 38,
        .msn_no = 131,
        .pos_x = 1837,
        .pos_y = 0,
        .pos_z = 1031,
        .get_msg = {13, 255},
    },
    {
        .item_no = 5,
        .stts = 0,
        .room = 38,
        .msn_no = 131,
        .pos_x = 2503,
        .pos_y = 0,
        .pos_z = 1371,
        .get_msg = {39, 255},
    },
    {
        .item_no = 8,
        .stts = 0,
        .room = 11,
        .msn_no = 131,
        .pos_x = 1880,
        .pos_y = 0,
        .pos_z = 2080,
        .get_msg = {11, 255},
    },
    {
        .item_no = 5,
        .stts = 0,
        .room = 40,
        .msn_no = 131,
        .pos_x = 809,
        .pos_y = 400,
        .pos_z = 1751,
        .get_msg = {43, 255},
    },
    {
        .item_no = 5,
        .stts = 0,
        .room = 16,
        .msn_no = 131,
        .pos_x = 1706,
        .pos_y = 0,
        .pos_z = 6137,
        .get_msg = {44, 255},
    },
    {
        .item_no = 2,
        .stts = 0,
        .room = 23,
        .msn_no = 131,
        .pos_x = 3070,
        .pos_y = 0,
        .pos_z = 510,
        .get_msg = {4, 255},
    },
    {
        .item_no = 8,
        .stts = 0,
        .room = 25,
        .msn_no = 131,
        .pos_x = 6014,
        .pos_y = -2025,
        .pos_z = 9016,
        .get_msg = {25, 255},
    },
    {
        .item_no = 4,
        .stts = 0,
        .room = 25,
        .msn_no = 131,
        .pos_x = 4130,
        .pos_y = -2025,
        .pos_z = 8944,
        .get_msg = {26, 255},
    },
    {
        .item_no = 6,
        .stts = 0,
        .room = 28,
        .msn_no = 132,
        .pos_x = 10393,
        .pos_y = 800,
        .pos_z = -2623,
        .get_msg = {32, 255},
    },
    {
        .item_no = 5,
        .stts = 0,
        .room = 28,
        .msn_no = 132,
        .pos_x = 3009,
        .pos_y = 0,
        .pos_z = 924,
        .get_msg = {25, 255},
    },
    {
        .item_no = 2,
        .stts = 0,
        .room = 29,
        .msn_no = 132,
        .pos_x = 526,
        .pos_y = 0,
        .pos_z = 526,
        .get_msg = {26, 255},
    },
    {
        .item_no = 8,
        .stts = 0,
        .room = 8,
        .msn_no = 132,
        .pos_x = 5800,
        .pos_y = 0,
        .pos_z = 1750,
        .get_msg = {34, 255},
    },
    {
        .item_no = 7,
        .stts = 0,
        .room = 9,
        .msn_no = 132,
        .pos_x = 180,
        .pos_y = -435,
        .pos_z = 2514,
        .get_msg = {37, 255},
    },
    {
        .item_no = 2,
        .stts = 0,
        .room = 9,
        .msn_no = 132,
        .pos_x = 4523,
        .pos_y = -1400,
        .pos_z = 2647,
        .get_msg = {36, 255},
    },
    {
        .item_no = 2,
        .stts = 0,
        .room = 1,
        .msn_no = 132,
        .pos_x = 4199,
        .pos_y = -50,
        .pos_z = 253,
        .get_msg = {18, 255},
    },
    {
        .item_no = 5,
        .stts = 0,
        .room = 3,
        .msn_no = 132,
        .pos_x = 2262,
        .pos_y = 30,
        .pos_z = 2220,
        .get_msg = {38, 255},
    },
    {
        .item_no = 2,
        .stts = 0,
        .room = 3,
        .msn_no = 132,
        .pos_x = 248,
        .pos_y = -1400,
        .pos_z = 158,
        .get_msg = {36, 255},
    },
    {
        .item_no = 5,
        .stts = 0,
        .room = 11,
        .msn_no = 132,
        .pos_x = 2393,
        .pos_y = 0,
        .pos_z = 4222,
        .get_msg = {11, 255},
    },
    {
        .item_no = 6,
        .stts = 0,
        .room = 24,
        .msn_no = 132,
        .pos_x = 6722,
        .pos_y = -1725,
        .pos_z = 1076,
        .get_msg = {27, 255},
    },
    {
        .item_no = 5,
        .stts = 0,
        .room = 2,
        .msn_no = 132,
        .pos_x = 149,
        .pos_y = 0,
        .pos_z = 3342,
        .get_msg = {7, 255},
    },
    {
        .item_no = 4,
        .stts = 0,
        .room = 36,
        .msn_no = 132,
        .pos_x = 1022,
        .pos_y = -450,
        .pos_z = 3200,
        .get_msg = {41, 255},
    },
    {
        .item_no = 6,
        .stts = 0,
        .room = 23,
        .msn_no = 132,
        .pos_x = 190,
        .pos_y = 0,
        .pos_z = 1500,
        .get_msg = {4, 255},
    },
    {
        .item_no = 8,
        .stts = 0,
        .room = 25,
        .msn_no = 132,
        .pos_x = 6014,
        .pos_y = -2025,
        .pos_z = 9016,
        .get_msg = {25, 255},
    },
    {
        .item_no = 3,
        .stts = 0,
        .room = 25,
        .msn_no = 132,
        .pos_x = 4130,
        .pos_y = -2025,
        .pos_z = 8944,
        .get_msg = {26, 255},
    },
    {
        .item_no = 6,
        .stts = 0,
        .room = 20,
        .msn_no = 132,
        .pos_x = 6600,
        .pos_y = -400,
        .pos_z = 2435,
        .get_msg = {45, 255},
    },
    {
        .item_no = 4,
        .stts = 0,
        .room = 14,
        .msn_no = 132,
        .pos_x = 1025,
        .pos_y = -2000,
        .pos_z = 3674,
        .get_msg = {46, 255},
    },
    {
        .item_no = 8,
        .stts = 0,
        .room = 14,
        .msn_no = 132,
        .pos_x = 2676,
        .pos_y = -1975,
        .pos_z = 1591,
        .get_msg = {47, 255},
    },
    {
        .item_no = 5,
        .stts = 0,
        .room = 31,
        .msn_no = 132,
        .pos_x = 2456,
        .pos_y = 0,
        .pos_z = 1126,
        .get_msg = {22, 255},
    },
    {
        .item_no = 7,
        .stts = 0,
        .room = 31,
        .msn_no = 132,
        .pos_x = 1113,
        .pos_y = 0,
        .pos_z = 2817,
        .get_msg = {22, 255},
    },
    {
        .item_no = 6,
        .stts = 0,
        .room = 30,
        .msn_no = 132,
        .pos_x = -757,
        .pos_y = 0,
        .pos_z = 40,
        .get_msg = {27, 255},
    },
    {
        .item_no = 2,
        .stts = 0,
        .room = 30,
        .msn_no = 132,
        .pos_x = 2697,
        .pos_y = 400,
        .pos_z = -5900,
        .get_msg = {48, 255},
    },
    {
        .item_no = 8,
        .stts = 0,
        .room = 32,
        .msn_no = 132,
        .pos_x = 5009,
        .pos_y = 50,
        .pos_z = 5669,
        .get_msg = {49, 255},
    },
    {
        .item_no = 5,
        .stts = 0,
        .room = 33,
        .msn_no = 132,
        .pos_x = -4703,
        .pos_y = 0,
        .pos_z = 6407,
        .get_msg = {25, 255},
    },
    {
        .item_no = 6,
        .stts = 0,
        .room = 33,
        .msn_no = 132,
        .pos_x = -2823,
        .pos_y = 0,
        .pos_z = 7926,
        .get_msg = {25, 255},
    },
    {
        .item_no = 7,
        .stts = 0,
        .room = 33,
        .msn_no = 132,
        .pos_x = 300,
        .pos_y = 0,
        .pos_z = 1284,
        .get_msg = {22, 255},
    },
};

u_char map_item_ap_type[][2] = {
    {1, 0}, {2, 0}, {2, 3}
};

MAP_FILE_DAT map_file_dat0[50] = {
    {
        .stts = 0,
        .room = 18,
        .pos_x = 1743,
        .pos_y = 0,
        .pos_z = 1682,
        .get_msg = {42, 39},
        .dsp_pct = 36,
        .msn_no = 4,
        .map_dsp = 1,
    },
    {
        .stts = 1,
        .room = 18,
        .pos_x = 2393,
        .pos_y = -200,
        .pos_z = 1874,
        .get_msg = {38, 39},
        .dsp_pct = 36,
        .msn_no = 4,
        .map_dsp = 0,
    },
    {
        .stts = 1,
        .room = 18,
        .pos_x = 2393,
        .pos_y = -200,
        .pos_z = 1874,
        .get_msg = {255, 39},
        .dsp_pct = 36,
        .msn_no = 4,
        .map_dsp = 0,
    },
    {
        .stts = 1,
        .room = 41,
        .pos_x = 256,
        .pos_y = -500,
        .pos_z = 1700,
        .get_msg = {41, 39},
        .dsp_pct = 36,
        .msn_no = 4,
        .map_dsp = 1,
    },
    {
        .stts = 1,
        .room = 41,
        .pos_x = 256,
        .pos_y = -500,
        .pos_z = 1700,
        .get_msg = {255, 39},
        .dsp_pct = 36,
        .msn_no = 4,
        .map_dsp = 1,
    },
    {
        .stts = 1,
        .room = 18,
        .pos_x = 973,
        .pos_y = -175,
        .pos_z = 1365,
        .get_msg = {40, 39},
        .dsp_pct = 36,
        .msn_no = 4,
        .map_dsp = 1,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 400,
        .pos_z = 0,
        .get_msg = {255, 255},
        .dsp_pct = 255,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 400,
        .pos_z = 0,
        .get_msg = {19, 20},
        .dsp_pct = 32,
        .msn_no = 1,
        .map_dsp = 0,
    },
    {
        .stts = 1,
        .room = 40,
        .pos_x = 1264,
        .pos_y = -7,
        .pos_z = 2040,
        .get_msg = {23, 24},
        .dsp_pct = 32,
        .msn_no = 2,
        .map_dsp = 1,
    },
    {
        .stts = 1,
        .room = 27,
        .pos_x = -4731,
        .pos_y = 0,
        .pos_z = 7825,
        .get_msg = {6, 27},
        .dsp_pct = 32,
        .msn_no = 2,
        .map_dsp = 1,
    },
    {
        .stts = 1,
        .room = 6,
        .pos_x = 3148,
        .pos_y = 0,
        .pos_z = 452,
        .get_msg = {23, 27},
        .dsp_pct = 32,
        .msn_no = 2,
        .map_dsp = 1,
    },
    {
        .stts = 1,
        .room = 38,
        .pos_x = 1089,
        .pos_y = -280,
        .pos_z = 820,
        .get_msg = {28, 27},
        .dsp_pct = 32,
        .msn_no = 2,
        .map_dsp = 1,
    },
    {
        .stts = 1,
        .room = 30,
        .pos_x = 9226,
        .pos_y = 400,
        .pos_z = -7741,
        .get_msg = {48, 27},
        .dsp_pct = 32,
        .msn_no = 4,
        .map_dsp = 1,
    },
    {
        .stts = 1,
        .room = 33,
        .pos_x = 60,
        .pos_y = 0,
        .pos_z = 1363,
        .get_msg = {44, 27},
        .dsp_pct = 32,
        .msn_no = 4,
        .map_dsp = 1,
    },
    {
        .stts = 0,
        .room = 16,
        .pos_x = 5963,
        .pos_y = 0,
        .pos_z = 3549,
        .get_msg = {44, 43},
        .dsp_pct = 36,
        .msn_no = 3,
        .map_dsp = 1,
    },
    {
        .stts = 0,
        .room = 22,
        .pos_x = 2992,
        .pos_y = 0,
        .pos_z = 11149,
        .get_msg = {45, 43},
        .dsp_pct = 36,
        .msn_no = 3,
        .map_dsp = 1,
    },
    {
        .stts = 0,
        .room = 21,
        .pos_x = 3300,
        .pos_y = 0,
        .pos_z = 5800,
        .get_msg = {46, 43},
        .dsp_pct = 36,
        .msn_no = 3,
        .map_dsp = 1,
    },
    {
        .stts = 0,
        .room = 6,
        .pos_x = 3232,
        .pos_y = 400,
        .pos_z = 2353,
        .get_msg = {47, 43},
        .dsp_pct = 36,
        .msn_no = 3,
        .map_dsp = 1,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 400,
        .pos_z = 0,
        .get_msg = {255, 255},
        .dsp_pct = 255,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 1,
        .room = 9,
        .pos_x = 176,
        .pos_y = -1100,
        .pos_z = 2701,
        .get_msg = {5, 30},
        .dsp_pct = 36,
        .msn_no = 1,
        .map_dsp = 0,
    },
    {
        .stts = 1,
        .room = 38,
        .pos_x = -1300,
        .pos_y = -400,
        .pos_z = 2706,
        .get_msg = {29, 30},
        .dsp_pct = 36,
        .msn_no = 2,
        .map_dsp = 1,
    },
    {
        .stts = 1,
        .room = 3,
        .pos_x = 310,
        .pos_y = -1400,
        .pos_z = 150,
        .get_msg = {31, 30},
        .dsp_pct = 36,
        .msn_no = 2,
        .map_dsp = 1,
    },
    {
        .stts = 1,
        .room = 38,
        .pos_x = -120,
        .pos_y = -600,
        .pos_z = 3300,
        .get_msg = {29, 30},
        .dsp_pct = 36,
        .msn_no = 2,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 400,
        .pos_z = 0,
        .get_msg = {255, 255},
        .dsp_pct = 255,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 1,
        .room = 40,
        .pos_x = 2600,
        .pos_y = -200,
        .pos_z = 2674,
        .get_msg = {25, 26},
        .dsp_pct = 21,
        .msn_no = 2,
        .map_dsp = 0,
    },
    {
        .stts = 1,
        .room = 11,
        .pos_x = 1296,
        .pos_y = 0,
        .pos_z = 108,
        .get_msg = {35, 26},
        .dsp_pct = 21,
        .msn_no = 2,
        .map_dsp = 0,
    },
    {
        .stts = 1,
        .room = 35,
        .pos_x = 366,
        .pos_y = -150,
        .pos_z = 1460,
        .get_msg = {32, 26},
        .dsp_pct = 21,
        .msn_no = 2,
        .map_dsp = 1,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 400,
        .pos_z = 0,
        .get_msg = {36, 37},
        .dsp_pct = 22,
        .msn_no = 2,
        .map_dsp = 1,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 400,
        .pos_z = 0,
        .get_msg = {255, 255},
        .dsp_pct = 255,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 3,
        .pos_x = 4949,
        .pos_y = 0,
        .pos_z = 1376,
        .get_msg = {34, 33},
        .dsp_pct = 33,
        .msn_no = 2,
        .map_dsp = 1,
    },
    {
        .stts = 1,
        .room = 3,
        .pos_x = 2741,
        .pos_y = -200,
        .pos_z = 1240,
        .get_msg = {10, 22},
        .dsp_pct = 50,
        .msn_no = 1,
        .map_dsp = 1,
    },
    {
        .stts = 1,
        .room = 15,
        .pos_x = 264,
        .pos_y = 0,
        .pos_z = 1245,
        .get_msg = {2, 3},
        .dsp_pct = 50,
        .msn_no = 1,
        .map_dsp = 1,
    },
    {
        .stts = 1,
        .room = 16,
        .pos_x = 5543,
        .pos_y = -400,
        .pos_z = 385,
        .get_msg = {2, 3},
        .dsp_pct = 50,
        .msn_no = 1,
        .map_dsp = 1,
    },
    {
        .stts = 0,
        .room = 17,
        .pos_x = 2160,
        .pos_y = 0,
        .pos_z = 559,
        .get_msg = {2, 3},
        .dsp_pct = 50,
        .msn_no = 1,
        .map_dsp = 1,
    },
    {
        .stts = 1,
        .room = 21,
        .pos_x = 400,
        .pos_y = -465,
        .pos_z = 6917,
        .get_msg = {21, 3},
        .dsp_pct = 50,
        .msn_no = 1,
        .map_dsp = 1,
    },
    {
        .stts = 0,
        .room = 25,
        .pos_x = 5209,
        .pos_y = -2025,
        .pos_z = 8500,
        .get_msg = {16, 17},
        .dsp_pct = 50,
        .msn_no = 1,
        .map_dsp = 1,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 400,
        .pos_z = 0,
        .get_msg = {255, 255},
        .dsp_pct = 255,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 1,
        .room = 41,
        .pos_x = 1535,
        .pos_y = -180,
        .pos_z = 2388,
        .get_msg = {18, 3},
        .dsp_pct = 30,
        .msn_no = 1,
        .map_dsp = 1,
    },
    {
        .stts = 1,
        .room = 8,
        .pos_x = 6283,
        .pos_y = -1400,
        .pos_z = 2484,
        .get_msg = {2, 3},
        .dsp_pct = 30,
        .msn_no = 1,
        .map_dsp = 1,
    },
    {
        .stts = 1,
        .room = 1,
        .pos_x = 1684,
        .pos_y = -50,
        .pos_z = 287,
        .get_msg = {2, 3},
        .dsp_pct = 30,
        .msn_no = 1,
        .map_dsp = 1,
    },
    {
        .stts = 1,
        .room = 7,
        .pos_x = 1496,
        .pos_y = -330,
        .pos_z = 1950,
        .get_msg = {18, 3},
        .dsp_pct = 30,
        .msn_no = 1,
        .map_dsp = 1,
    },
    {
        .stts = 0,
        .room = 10,
        .pos_x = 2020,
        .pos_y = -280,
        .pos_z = 700,
        .get_msg = {18, 3},
        .dsp_pct = 30,
        .msn_no = 1,
        .map_dsp = 1,
    },
    {
        .stts = 1,
        .room = 17,
        .pos_x = 1400,
        .pos_y = 0,
        .pos_z = 4421,
        .get_msg = {2, 3},
        .dsp_pct = 33,
        .msn_no = 1,
        .map_dsp = 1,
    },
    {
        .stts = 0,
        .room = 23,
        .pos_x = 3005,
        .pos_y = 0,
        .pos_z = 5011,
        .get_msg = {2, 3},
        .dsp_pct = 30,
        .msn_no = 1,
        .map_dsp = 1,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 400,
        .pos_z = 0,
        .get_msg = {255, 255},
        .dsp_pct = 255,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 400,
        .pos_z = 0,
        .get_msg = {255, 255},
        .dsp_pct = 32,
        .msn_no = 1,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 400,
        .pos_z = 0,
        .get_msg = {255, 255},
        .dsp_pct = 32,
        .msn_no = 1,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 400,
        .pos_z = 0,
        .get_msg = {255, 255},
        .dsp_pct = 32,
        .msn_no = 1,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 1200,
        .pos_y = -400,
        .pos_z = 5188,
        .get_msg = {6, 7},
        .dsp_pct = 33,
        .msn_no = 1,
        .map_dsp = 1,
    },
    {
        .stts = 1,
        .room = 13,
        .pos_x = 4176,
        .pos_y = 0,
        .pos_z = 5106,
        .get_msg = {6, 7},
        .dsp_pct = 32,
        .msn_no = 1,
        .map_dsp = 1,
    },
};

MAP_FILE_DAT map_file_dat1[50] = {
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 400,
        .pos_z = 0,
        .get_msg = {2, 255},
        .dsp_pct = 33,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 400,
        .pos_z = 0,
        .get_msg = {2, 255},
        .dsp_pct = 33,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
};

MAP_FILE_DAT map_file_dat2[50] = {
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 400,
        .pos_z = 0,
        .get_msg = {255, 255},
        .dsp_pct = 255,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 400,
        .pos_z = 0,
        .get_msg = {15, 6},
        .dsp_pct = 51,
        .msn_no = 1,
        .map_dsp = 0,
    },
    {
        .stts = 1,
        .room = 15,
        .pos_x = 820,
        .pos_y = 0,
        .pos_z = 2544,
        .get_msg = {13, 6},
        .dsp_pct = 51,
        .msn_no = 1,
        .map_dsp = 1,
    },
    {
        .stts = 1,
        .room = 14,
        .pos_x = 2338,
        .pos_y = -100,
        .pos_z = 3900,
        .get_msg = {25, 6},
        .dsp_pct = 51,
        .msn_no = 3,
        .map_dsp = 1,
    },
    {
        .stts = 1,
        .room = 7,
        .pos_x = 289,
        .pos_y = -400,
        .pos_z = 330,
        .get_msg = {36, 6},
        .dsp_pct = 51,
        .msn_no = 1,
        .map_dsp = 1,
    },
    {
        .stts = 1,
        .room = 7,
        .pos_x = 3998,
        .pos_y = -330,
        .pos_z = 1930,
        .get_msg = {38, 6},
        .dsp_pct = 51,
        .msn_no = 2,
        .map_dsp = 1,
    },
    {
        .stts = 1,
        .room = 28,
        .pos_x = 6424,
        .pos_y = 1050,
        .pos_z = -8250,
        .get_msg = {39, 6},
        .dsp_pct = 51,
        .msn_no = 3,
        .map_dsp = 1,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 400,
        .pos_z = 0,
        .get_msg = {255, 255},
        .dsp_pct = 255,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 400,
        .pos_z = 0,
        .get_msg = {255, 255},
        .dsp_pct = 255,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 400,
        .pos_z = 0,
        .get_msg = {255, 255},
        .dsp_pct = 255,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 1,
        .room = 14,
        .pos_x = 1020,
        .pos_y = -180,
        .pos_z = 4014,
        .get_msg = {25, 24},
        .dsp_pct = 51,
        .msn_no = 4,
        .map_dsp = 1,
    },
    {
        .stts = 1,
        .room = 14,
        .pos_x = 3678,
        .pos_y = -180,
        .pos_z = 4014,
        .get_msg = {25, 24},
        .dsp_pct = 51,
        .msn_no = 4,
        .map_dsp = 1,
    },
    {
        .stts = 1,
        .room = 14,
        .pos_x = 2343,
        .pos_y = -120,
        .pos_z = 2950,
        .get_msg = {26, 24},
        .dsp_pct = 51,
        .msn_no = 4,
        .map_dsp = 1,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 400,
        .pos_z = 0,
        .get_msg = {255, 255},
        .dsp_pct = 255,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 1,
        .room = 38,
        .pos_x = 350,
        .pos_y = -100,
        .pos_z = 350,
        .get_msg = {17, 8},
        .dsp_pct = 35,
        .msn_no = 1,
        .map_dsp = 1,
    },
    {
        .stts = 1,
        .room = 1,
        .pos_x = 6796,
        .pos_y = -50,
        .pos_z = 500,
        .get_msg = {7, 8},
        .dsp_pct = 35,
        .msn_no = 1,
        .map_dsp = 1,
    },
    {
        .stts = 1,
        .room = 9,
        .pos_x = 4420,
        .pos_y = -1400,
        .pos_z = 2400,
        .get_msg = {16, 8},
        .dsp_pct = 35,
        .msn_no = 1,
        .map_dsp = 0,
    },
    {
        .stts = 1,
        .room = 17,
        .pos_x = 3038,
        .pos_y = -1900,
        .pos_z = 5214,
        .get_msg = {7, 8},
        .dsp_pct = 35,
        .msn_no = 1,
        .map_dsp = 1,
    },
    {
        .stts = 1,
        .room = 29,
        .pos_x = 4881,
        .pos_y = 3000,
        .pos_z = 4224,
        .get_msg = {20, 8},
        .dsp_pct = 35,
        .msn_no = 2,
        .map_dsp = 1,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 400,
        .pos_z = 0,
        .get_msg = {21, 8},
        .dsp_pct = 35,
        .msn_no = 2,
        .map_dsp = 0,
    },
    {
        .stts = 1,
        .room = 5,
        .pos_x = 1720,
        .pos_y = -400,
        .pos_z = 2373,
        .get_msg = {22, 8},
        .dsp_pct = 35,
        .msn_no = 2,
        .map_dsp = 1,
    },
    {
        .stts = 0,
        .room = 28,
        .pos_x = 3865,
        .pos_y = 0,
        .pos_z = 827,
        .get_msg = {27, 29},
        .dsp_pct = 35,
        .msn_no = 3,
        .map_dsp = 1,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 400,
        .pos_z = 0,
        .get_msg = {28, 29},
        .dsp_pct = 35,
        .msn_no = 3,
        .map_dsp = 0,
    },
    {
        .stts = 1,
        .room = 3,
        .pos_x = 4500,
        .pos_y = -400,
        .pos_z = 724,
        .get_msg = {9, 29},
        .dsp_pct = 35,
        .msn_no = 3,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 400,
        .pos_z = 0,
        .get_msg = {255, 255},
        .dsp_pct = 255,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 400,
        .pos_z = 0,
        .get_msg = {255, 255},
        .dsp_pct = 255,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 1,
        .room = 3,
        .pos_x = 2741,
        .pos_y = -200,
        .pos_z = 1240,
        .get_msg = {23, 18},
        .dsp_pct = 55,
        .msn_no = 1,
        .map_dsp = 1,
    },
    {
        .stts = 1,
        .room = 12,
        .pos_x = 400,
        .pos_y = -650,
        .pos_z = 360,
        .get_msg = {19, 3},
        .dsp_pct = 55,
        .msn_no = 1,
        .map_dsp = 1,
    },
    {
        .stts = 0,
        .room = 8,
        .pos_x = 5800,
        .pos_y = 0,
        .pos_z = 1750,
        .get_msg = {12, 3},
        .dsp_pct = 54,
        .msn_no = 1,
        .map_dsp = 1,
    },
    {
        .stts = 1,
        .room = 9,
        .pos_x = 559,
        .pos_y = -500,
        .pos_z = 3200,
        .get_msg = {14, 3},
        .dsp_pct = 53,
        .msn_no = 1,
        .map_dsp = 0,
    },
    {
        .stts = 1,
        .room = 17,
        .pos_x = -1495,
        .pos_y = -1400,
        .pos_z = 477,
        .get_msg = {2, 3},
        .dsp_pct = 53,
        .msn_no = 1,
        .map_dsp = 1,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 400,
        .pos_z = 0,
        .get_msg = {2, 3},
        .dsp_pct = 55,
        .msn_no = 1,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 400,
        .pos_z = 0,
        .get_msg = {2, 3},
        .dsp_pct = 55,
        .msn_no = 1,
        .map_dsp = 0,
    },
    {
        .stts = 1,
        .room = 0,
        .pos_x = 3958,
        .pos_y = -400,
        .pos_z = 4885,
        .get_msg = {255, 37},
        .dsp_pct = 9,
        .msn_no = 0,
        .map_dsp = 1,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 400,
        .pos_z = 0,
        .get_msg = {255, 37},
        .dsp_pct = 9,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 400,
        .pos_z = 0,
        .get_msg = {255, 37},
        .dsp_pct = 9,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 400,
        .pos_z = 0,
        .get_msg = {255, 37},
        .dsp_pct = 9,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
};

MAP_FILE_DAT map_file_dat3[50] = {
    {
        .stts = 0,
        .room = 50,
        .pos_x = 2500,
        .pos_y = 0,
        .pos_z = 2925,
        .get_msg = {2, 255},
        .dsp_pct = 34,
        .msn_no = 1,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 50,
        .pos_x = 2500,
        .pos_y = 0,
        .pos_z = 2925,
        .get_msg = {2, 255},
        .dsp_pct = 34,
        .msn_no = 1,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
    {
        .stts = 0,
        .room = 0,
        .pos_x = 0,
        .pos_y = 0,
        .pos_z = 0,
        .get_msg = {0, 0},
        .dsp_pct = 0,
        .msn_no = 0,
        .map_dsp = 0,
    },
};

MAP_FILE_DAT *map_file_dat[4] = {
    map_file_dat0, map_file_dat1,
    map_file_dat2, map_file_dat3,
};
u_short item_ap[300][2] = {0};

#define PI 3.1415927f

void MapItemInit()
{
    int i;

    for (i = 0; i < 162; i++)
    {
        if (ingame_wrk.game == 1)
        {
            item_ap[i][0] = 1;
            item_ap[i][1] = 1;
        }
        else if ((map_item_dat[i].stts & 0x1) == 0)
        {
            item_ap[i][0] = 0;
            item_ap[i][1] = 0;
        }
        else
        {
            item_ap[i][0] = 1;
            item_ap[i][1] = 1;
        }
    }
}

void MissionStartMapItemInit(int msn_no)
{
    int i;

    for (i = 0; i < 162; i++)
    {
        if ((map_item_dat[i].msn_no & 0x80) != 0)
        {
            if (msn_no == (map_item_dat[i].msn_no & 0x7f))
            {
                if ((map_item_dat[i].stts & 1) == 0)
                {
                    item_ap[i][0] = 0;
                    item_ap[i][1] = 0;
                }
                else
                {
                    item_ap[i][0] = 1;
                    item_ap[i][1] = 1;
                }
            }
            else
            {
                item_ap[i][0] = 1;
                item_ap[i][1] = 1;
            }
        }
        else if (msn_no == map_item_dat[i].msn_no)
        {
            item_ap[i][0] = 0;
            item_ap[i][1] = 0;
        }
    }

    for (i = 0; i < 50; i++)
    {
        if (map_file_dat0[i].msn_no == msn_no)
        {
            if (ingame_wrk.clear_count == 0)
            {
                poss_file[0][i] = map_file_dat0[i].stts;
            }
            else if (poss_file[0][i] < 2)
            {
                poss_file[0][i] = map_file_dat0[i].stts;
            }
        }
        else
        {
            if (poss_file[0][i] == 1)
            {
                poss_file[0][i] = 0;
            }
        }
    }

    for (i = 0; i < 50; i++)
    {
        if (map_file_dat1[i].msn_no == msn_no)
        {
            if (ingame_wrk.clear_count == 0)
            {
                poss_file[1][i] = map_file_dat1[i].stts;
            }
        }
        else
        {
            if (poss_file[1][i] == 1)
            {
                poss_file[1][i] = 0;
            }
        }
    }

    for (i = 0; i < 50; i++)
    {
        if (map_file_dat2[i].msn_no == msn_no)
        {
            if (ingame_wrk.clear_count == 0x0)
            {
                poss_file[2][i]  = map_file_dat2[i].stts;
            }
            else if (poss_file[2][i] < 2)
            {
                poss_file[2][i]  = map_file_dat2[i].stts;
            }
        }
        else
        {
            if (poss_file[2][i] == 1)
            {
                poss_file[2][i] = 0;
            }
        }
    }

    for (i = 0; i < 50; i++)
    {
        if (map_file_dat3[i].msn_no == msn_no)
        {
            if (ingame_wrk.clear_count == 0)
            {
                poss_file[3][i] = map_file_dat3[i].stts;
            }
        }
        else
        {
            if (poss_file[3][i] == 1)
            {
                poss_file[3][i] = 0;
            }
            else if (poss_file[3][i] < 2)
            {
                poss_file[3][i] = map_file_dat3[i].stts;
            }
        }
    }
}

void FileDateInit()
{
    int i;

    for (i = 0; i < 50; i++)
    {
        poss_file[0][i] = map_file_dat0[i].stts;
    }

    for (i = 0; i < 50; i++)
    {
        poss_file[1][i] = map_file_dat1[i].stts;
    }

    for (i = 0; i < 50; i++)
    {
        poss_file[2][i] = map_file_dat2[i].stts;
    }

    for (i = 0; i < 50; i++)
    {
        poss_file[3][i] = map_file_dat3[i].stts;
    }
}

int ItemGetMain()
{
    int get_item;

    get_item = 0xffff;

    if (
        ingame_wrk.mode == INGAME_MODE_NOMAL && plyr_wrk.mode == PMODE_NORMAL &&
        (ingame_wrk.stts & 0x80) == 0 && (plyr_wrk.sta & 0x8) == 0 &&
        find_wrk.mode == 0 && *key_now[5] == 1
    )
    {
        get_item = GetMapItemJudge();
    }

    if (get_item != 0xffff)
    {
        GetMapItem(get_item);

        return 1;
    }

    return 0;
}

void ItemCtrl()
{
    if (ev_wrk.get_item == 0)
    {
        ItemDispCtrl();
        FilmPossessionExp();
    }
    else
    {
        plyr_wrk.mode = PMODE_MSG_DISP;

        eff_blur_off = 1;
    }
}

void ItemDispCtrl()
{
    int i;

    for (i = 0; i < 2; i++)
    {
        if (room_wrk.disp_no[i] != room_wrk.disp_bak[i])
        {
            SetItemDispData(i);
        }
    }
}

void SetItemDispData(u_char id)
{
    int i;
    int j;
    int dsp_no;
    int item_no;

    if (id >= 2)
    {
        return;
    }

    for (i = 0; i < 16; i++)
    {
        item_dsp_wrk[id][i].item_no = -1;
    }

    if (room_wrk.disp_no[id] == 0xff)
    {
        return;
    }

    for (i = 0, dsp_no = 0; i < 162; i++)
    {
        if (item_ap[i][0] == 0 && item_ap[i][1] == 0)
        {
            if (map_item_dat[i].room == room_wrk.disp_no[id])
            {
                if ((map_item_dat[i].stts & 2) != 0)
                {
                    item_dsp_wrk[id][dsp_no].disp = 0;
                }
                else
                {
                    item_dsp_wrk[id][dsp_no].disp = 1;
                }

                item_dsp_wrk[id][dsp_no].item_no = i;

                item_dsp_wrk[id][dsp_no].pos[0] = map_item_dat[i].pos_x + room_wrk.pos[id][0];
                item_dsp_wrk[id][dsp_no].pos[1] = map_item_dat[i].pos_y + room_wrk.pos[id][1];
                item_dsp_wrk[id][dsp_no].pos[2] = map_item_dat[i].pos_z + room_wrk.pos[id][2];

                dsp_no++;

                if (dsp_no > 15)
                {
                    return;
                }
            }
        }
    }

    for (i = 0; i < 4; i++)
    {
        item_no = i * 0x2000 - 0x8000;

        for (j = 0; j < 50; item_no++, j++)
        {
            if (poss_file[i][j] == 1)
            {
                if (map_file_dat[i][j].room == room_wrk.disp_no[id])
                {
                    item_dsp_wrk[id][dsp_no].disp = map_file_dat[i][j].map_dsp;

                    item_dsp_wrk[id][dsp_no].item_no = item_no;

                    item_dsp_wrk[id][dsp_no].pos[0] = map_file_dat[i][j].pos_x + room_wrk.pos[id][0];
                    item_dsp_wrk[id][dsp_no].pos[1] = map_file_dat[i][j].pos_y + room_wrk.pos[id][1];
                    item_dsp_wrk[id][dsp_no].pos[2] = map_file_dat[i][j].pos_z + room_wrk.pos[id][2];

                    dsp_no++;

                    if (dsp_no > 15)
                    {
                        return;
                    }
                }
            }
        }
    }
}

void ItemDispDataRenew()
{
    int i;

    for (i = 0; i < 2; i++)
    {
        SetItemDispData(i);
    }
}

int GetMapItemJudge()
{
    int i;
    int j;

    for (i = 0; i < 2; i++)
    {
        if (room_wrk.disp_no[i] != 0xff)
        {
            for (j = 0; j < 16; j++) {
                if (item_dsp_wrk[i][j].item_no < 0x8000 && map_item_dat[item_dsp_wrk[i][j].item_no].stts & 0x80)
                {
                    continue;
                }

                if (item_dsp_wrk[i][j].item_no == 0xffff)
                {
                    continue;
                }

                if (
                    item_dsp_wrk[i][j].pos[1] < (int)(plyr_wrk.move_box.pos[1] + 500.0f) &&
                    item_dsp_wrk[i][j].pos[1] > (int)(plyr_wrk.move_box.pos[1] - 1000.0f)
                )
                {
                    if (OutSightChk(item_dsp_wrk[i][j].pos, plyr_wrk.move_box.pos, plyr_wrk.move_box.rot[1], PI / 2, 300.0f) == 0)
                    {
                        return item_dsp_wrk[i][j].item_no;
                    }

                    if (OutSightChk(item_dsp_wrk[i][j].pos, plyr_wrk.move_box.pos, plyr_wrk.move_box.rot[1], PI, 100.0f) == 0)
                    {
                        return item_dsp_wrk[i][j].item_no;
                    }
                }
            }
        }
    }

    return 0xffff;
}

void GetMapItem(u_short get_no)
{
    int tmp;
    u_char i;
    u_char j;

    plyr_wrk.mode = PMODE_MSG_DISP;

    eff_blur_off = 1;

    ingame_wrk.mode = INGAME_MODE_GET_ITEM;

    if (get_no & 0x8000)
    {
        tmp = get_no - ((get_no - 0x8000 < 0) ? 0x6001 : 0x8000);

        i = (tmp >> 13) & 0xff;
        j = get_no & 0xff;

        ItemGet(i, get_no, map_file_dat[i][j].get_msg[0], map_file_dat[i][j].get_msg[1]);

        poss_file[i][j] = 2;
    }
    else
    {
        ItemGet(4, map_item_dat[get_no].item_no, map_item_dat[get_no].get_msg[0], map_item_dat[get_no].get_msg[1]);

        if (map_item_dat[get_no].item_no == 8)
        {
            if (poss_item[map_item_dat[get_no].item_no] == 0)
            {
                poss_item[map_item_dat[get_no].item_no] = 1;

                item_ap[get_no][0] = 1;
                item_ap[get_no][1] = 1;
            }
        }
        else
        {
            if (poss_item[map_item_dat[get_no].item_no] != 0x63)
            {
                if (map_item_dat[get_no].item_no < 5)
                {
                    poss_item[map_item_dat[get_no].item_no] += 12;

                    if (poss_item[map_item_dat[get_no].item_no] > 99)
                    {
                        poss_item[map_item_dat[get_no].item_no] = 99;
                    }
                }
                else
                {
                    poss_item[map_item_dat[get_no].item_no]++;
                }

                item_ap[get_no][0] = 1;
                item_ap[get_no][1] = 1;
            }
        }
    }

    ItemDispDataRenew();
}

void ItemAppearCtrl()
{
    return;
}

int ItemGetContinueJudge()
{
    int get_item;

    get_item = GetMapItemJudge();

    if (get_item != 0xFFFF)
    {
        GetMapItem(get_item);

        return 1;
    }

    return 0;
}
